# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunttestbucketinwizlabenvfrombartek"
    dynamodb_table = "tf-locks"
    encrypt        = true
    key            = "prod/us-east-1/prod/mysql/tf.tfstate"
    region         = "us-east-1"
  }
}
